apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: logicapps-k8s-v0
  name: logicapps-k8s-v0
  namespace: logicapps-v0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logicapps-k8s-v0
  template:
    metadata:
      labels:
        app: logicapps-k8s-v0
    spec:
      containers:
      - env:
        - name: WEBSITE_SITE_NAME
          value: helloworkflow
        - name: WEBSITE_HOSTNAME
          value: localhost
        - name: AzureWebJobsStorage
          value: DefaultEndpointsProtocol=https;AccountName=logicappstateweu;AccountKey=PFxqQ9aGldiuvLEms2wG8GgUjs7IHAD3hMo9SNIA2opmoJy+oIdjSs+J9TUstGqVN9Ce4Dq4ig50+AStG+jAOw==;EndpointSuffix=core.windows.net
        - name: APPINSIGHTS_INSTRUMENTATIONKEY
          value: 556bd798-0734-4dae-a0a0-66d4ed23dff8
        - name: AZURE_FUNCTIONS_ENVIRONMENT
          value: Development
        - name: AzureFunctionsJobHost__extensionBundle__version
          value: '[1.*, 2.0.0)'
        - name: AzureFunctionsJobHost__extensionBundle__id
          value: Microsoft.Azure.Functions.ExtensionBundle.Workflows
        - name: tracing__consoleLevel
          value: verbose
        image: massimocrippa/la-standard-dotnet:0.0.6-s1
        imagePullPolicy: IfNotPresent
        name: logicapps-k8s-v0-img
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 250m
            memory: 250Mi
          limits:
            memory: 400Mi
      securityContext: {}
      terminationGracePeriodSeconds: 60