apiVersion: v1
kind: Service
metadata:
  labels:
    app: logicapps-k8s-v0
  name: logicapps-k8s-v0-http
  namespace: logicapps-v0
spec:
  ports:
    - name: wf
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: logicapps-k8s-v0
  type: ClusterIP